version: "3.9"
services:
  iot-rgb-led-matrix:
    image: iot_rgb_led_matrix
    build: .
    restart: always
    environment:
      - HOST_IP=192.168.3.15
      - PORT=7777
      - ANIMATION=analog_clock.AnalogClock
      - TZ=Asia/Tokyo
      - KEY=OPENWEATHERMAP_API_KEY
      - CITY=Tokyo
      - TEXT=test
    volumes:
      - .:/root/ws
