version: "3.6"
services:
  iot-rgb-led-matrix:
    container_name: client
    image: iot_rgb_led_matrix
    build: .
    restart: unless-stopped
    environment:
      - HOST_IP=192.168.3.25
      - PORT=7777
      - ANIMATION=rgb.GrowingTree
      - TZ=Asia/Tokyo
      - KEY=OPENWEATHERMAP_API_KEY
      - CITY=Tokyo
      - TEXT=test
