name: CI

on: [push, pull_request]

# Linting: OK
# Dockerfile linting: OK
# Pytest: OK
# Doxygen

# PyPi?
# Black?
# setup.py?

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: Dockerfile
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-pylint
      - name: Test and lint
        env:
          PYTHONPATH: ${{ github.workspace }}/client
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        run: |
          cd client
          pytest
  document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate Doxygen documentation
        uses: mattnotmitt/doxygen-action@v1.1.0
      - name: Publish Doxygen to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html/
