name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        run: docker-compose build --pull --no-cache
      - name: Start container
        run: docker-compose up -d
      - name: Install test suite
        run: docker exec client pip install coveralls pytest pytest-cov pytest-pylint pytest-black
      - name: Test and lint
        run: docker exec -e OPENWEATHERMAP_API_KEY=${{ secrets.OPENWEATHERMAP_API_KEY }} client pytest client
      - name: Stop container
        run: docker-compose down
      - name: Coveralls
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          pip install coveralls
          coveralls
