name: docker

on: [push, pull_request]

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Dockerfile linting.
      #- name: ?
      #  uses: ?
