name: document

on: [push, pull_request]

jobs:
  document:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ env.GITHUB_REF }}
      COMMIT: ${{ env.GITHUB_SHA }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate Doxygen documentation
        uses: mattnotmitt/doxygen-action@v1.1.0
      - name: Publish Doxygen to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html/
