name: CI

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: python:3.9
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: pip install pytest pytest-pylint
      - name: Test
        run: cd client && pytest
