name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Start Docker componse
        run: docker-compose run iot-rgb-led-matrix bash
      - name: Test and lint
        env:
          PYTHONPATH: ${{ github.workspace }}/client
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-pylint
          cd client
          pytest
